### ISSUE TITLE
Feature Request: Color should be able to support hexadecimal values

### ISSUE THREAD

**Issue by astranono** [GameEngineDesign-S24/AstraEngine#12]
Color.cs should be able to support hexadecimal values for colors. This could be implemented in a way that converts it to RGB.

**Comment by jcollard** [comment]
I think this would be an excellent addition. Take a look at `AstraEngine.Canvas2D.Color`. I think a static extension method for strings would be great to have:

```
"FF00FFFF".ToColor();
```
