### ISSUE TITLE
Investigation: Create test 3d scene for testing 3d rendering.

### ISSUE THREAD

**Issue by astranono** [GameEngineDesign-S24/AstraEngine#21]
This should be made in blender, and have a material applied. This will be used to test future 3d rendering with our engine.

**Comment by jcollard** [comment]
Nice idea! It might make sense to make an `ICanvas3D` that extends `ICanvas2D` as well as a `View3D` that follows a similar pattern as the `View` component.

**Comment by astranono** [comment]
I finished the model. I am not sure how to implement it into the official version so I will do that with you in class.

**Comment by jcollard** [comment]
Great! Typically, you we leave issues open until something has been merged into the project (or it is decided that it won't be implemented). Did you mean to close this issue?
